// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: fine.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FinesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *FinesRequest) Reset() {
	*x = FinesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinesRequest) ProtoMessage() {}

func (x *FinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinesRequest.ProtoReflect.Descriptor instead.
func (*FinesRequest) Descriptor() ([]byte, []int) {
	return file_fine_proto_rawDescGZIP(), []int{0}
}

func (x *FinesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FinesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Items  []*Fine `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *FinesResponse) Reset() {
	*x = FinesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinesResponse) ProtoMessage() {}

func (x *FinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinesResponse.ProtoReflect.Descriptor instead.
func (*FinesResponse) Descriptor() ([]byte, []int) {
	return file_fine_proto_rawDescGZIP(), []int{1}
}

func (x *FinesResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FinesResponse) GetItems() []*Fine {
	if x != nil {
		return x.Items
	}
	return nil
}

type Fine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount  int64                `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Number  string               `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	Created *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *Fine) Reset() {
	*x = Fine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fine) ProtoMessage() {}

func (x *Fine) ProtoReflect() protoreflect.Message {
	mi := &file_fine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fine.ProtoReflect.Descriptor instead.
func (*Fine) Descriptor() ([]byte, []int) {
	return file_fine_proto_rawDescGZIP(), []int{2}
}

func (x *Fine) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Fine) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Fine) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Fine) GetCreated() *timestamp.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

var File_fine_proto protoreflect.FileDescriptor

var file_fine_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x76,
	0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x26, 0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x58, 0x0a, 0x0d, 0x46, 0x69,
	0x6e, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x65, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x7c, 0x0a, 0x04, 0x46, 0x69, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x32, 0x64, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x55, 0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x21, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x66, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x19, 0x5a, 0x17, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x66, 0x69, 0x6e, 0x65,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fine_proto_rawDescOnce sync.Once
	file_fine_proto_rawDescData = file_fine_proto_rawDesc
)

func file_fine_proto_rawDescGZIP() []byte {
	file_fine_proto_rawDescOnce.Do(func() {
		file_fine_proto_rawDescData = protoimpl.X.CompressGZIP(file_fine_proto_rawDescData)
	})
	return file_fine_proto_rawDescData
}

var file_fine_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_fine_proto_goTypes = []interface{}{
	(*FinesRequest)(nil),        // 0: lectiongrpc.fine.v1.FinesRequest
	(*FinesResponse)(nil),       // 1: lectiongrpc.fine.v1.FinesResponse
	(*Fine)(nil),                // 2: lectiongrpc.fine.v1.Fine
	(*timestamp.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_fine_proto_depIdxs = []int32{
	2, // 0: lectiongrpc.fine.v1.FinesResponse.items:type_name -> lectiongrpc.fine.v1.Fine
	3, // 1: lectiongrpc.fine.v1.Fine.created:type_name -> google.protobuf.Timestamp
	0, // 2: lectiongrpc.fine.v1.FineService.FindByUserId:input_type -> lectiongrpc.fine.v1.FinesRequest
	1, // 3: lectiongrpc.fine.v1.FineService.FindByUserId:output_type -> lectiongrpc.fine.v1.FinesResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fine_proto_init() }
func file_fine_proto_init() {
	if File_fine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fine_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fine_proto_goTypes,
		DependencyIndexes: file_fine_proto_depIdxs,
		MessageInfos:      file_fine_proto_msgTypes,
	}.Build()
	File_fine_proto = out.File
	file_fine_proto_rawDesc = nil
	file_fine_proto_goTypes = nil
	file_fine_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FineServiceClient is the client API for FineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FineServiceClient interface {
	FindByUserId(ctx context.Context, in *FinesRequest, opts ...grpc.CallOption) (*FinesResponse, error)
}

type fineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFineServiceClient(cc grpc.ClientConnInterface) FineServiceClient {
	return &fineServiceClient{cc}
}

func (c *fineServiceClient) FindByUserId(ctx context.Context, in *FinesRequest, opts ...grpc.CallOption) (*FinesResponse, error) {
	out := new(FinesResponse)
	err := c.cc.Invoke(ctx, "/lectiongrpc.fine.v1.FineService/FindByUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FineServiceServer is the server API for FineService service.
type FineServiceServer interface {
	FindByUserId(context.Context, *FinesRequest) (*FinesResponse, error)
}

// UnimplementedFineServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFineServiceServer struct {
}

func (*UnimplementedFineServiceServer) FindByUserId(context.Context, *FinesRequest) (*FinesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByUserId not implemented")
}

func RegisterFineServiceServer(s *grpc.Server, srv FineServiceServer) {
	s.RegisterService(&_FineService_serviceDesc, srv)
}

func _FineService_FindByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FineServiceServer).FindByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lectiongrpc.fine.v1.FineService/FindByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FineServiceServer).FindByUserId(ctx, req.(*FinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FineService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lectiongrpc.fine.v1.FineService",
	HandlerType: (*FineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindByUserId",
			Handler:    _FineService_FindByUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fine.proto",
}
