version: '3.7'
services:
  bankdb:
    image: mongo:4.4
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=db
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

