### Получение списка всех объявлений

GET http://localhost:9999/offers

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received '" + response.contentType.mimeType + "'");
});
%}

### Создание нового сообщения (id = 0)

POST http://localhost:9999/offers
Content-Type: application/json

{
  "id": 0,
  "company": "Delivery Club",
  "percent": "35%",
  "comment": "на первую покупку"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received '" + response.contentType.mimeType + "'");
  client.global.set("offerId", parseInt(response.body.id));
});
%}

### Получение предложения по id (переменная offerId берётся из предыдущего запроса: client.global.set("offerId", response.body.id)

GET http://localhost:9999/offers/{{offerId}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received '" + response.contentType.mimeType + "'");
  client.assert(response.body.company === "Delivery Club", "Invalid company");
});
%}

### Обновление предложения (id != 0)

POST http://localhost:9999/offers
Content-Type: application/json

{
  "id": {{offerId}},
  "company": "Delivery Club",
  "percent": "40%",
  "comment": "на первую покупку"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received '" + response.contentType.mimeType + "'");
  client.assert(response.body.percent === "40%", "Percent not updated");
});
%}

