# переменные заданы в файле .env
version: '3.7'
services:
  backend:
    build:
      context: services/backend
    image: backend
    ports:
      - 9999:9999
    environment:
      - APP_CONSUL_URL=http://consul:8500
    networks:
      micro-net:
    dns:
      - ${DNS_IP}
  auth:
    build:
      context: services/auth
    image: auth
    environment:
      - APP_CONSUL_URL=http://consul:8500
      - APP_DSN=postgres://app:pass@authdb:5432/db
      - APP_IP=${AUTH_IP}
    networks:
      micro-net:
        ipv4_address: ${AUTH_IP}
    dns:
      - ${DNS_IP}
  authdb:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=db
    volumes:
      - ./services/auth/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    networks:
      micro-net:
    dns:
      - ${DNS_IP}
  transactions:
    build:
      context: services/transactions
    image: service
    environment:
      - APP_CONSUL_URL=http://consul:8500
      - APP_IP=${TRANSACTIONS_IP}
    networks:
      micro-net:
        ipv4_address: ${TRANSACTIONS_IP}
    dns:
      - ${DNS_IP}
  consul:
    image: consul:1.8.4
    command: agent -server -ui -node=server -bootstrap-expect=1 -client=0.0.0.0 -recursor=8.8.8.8 -dns-port=53
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=
    ports:
      - 8500:8500
    networks:
      micro-net:
        ipv4_address: ${DNS_IP}
  jaeger:
    image: jaegertracing/all-in-one:1.20
    ports:
      - 16686:16686
    networks:
      micro-net:
    dns:
      - ${DNS_IP}
networks:
  micro-net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
